#!/bin/bash
cd $(dirname $0)/..

source ./auto/set-env

./auto/build

# Add parameters to cloudformation config file using stackup
stackup ${STACK_NAME} up -t aws/cloudformation/template.yml \
  -p aws/cloudformation/params.yml
  