#! /bin/bash -ex
cd $(dirname $0)/..

source ./auto/set-env

step_info "1. Create a lambda function using the zipped code file"
aws lambda create-function --function-name ${LAMBDA_FUNCTION_NAME} \
  --runtime pythhon3.8 --role arn:aws:iam::494526681395:role/for-aws-training \
  --zip-file fileb://./src/index.zip

step_info "2. Create S3 resoure bucket"
aws s3 mb s3://${S3_SOURCE_BUCKET_NAME}

step_info "3. Add a csv file to resource bucket"
aws s3 cp ./files/BAU_Roster.csv s3://${S3_SOURCE_BUCKET_NAME}

step_info "4. Create S3 target bucket"
aws s3 mb s3://${S3_TARGET_BUCKET_NAME}

step_info "5. Invoke the lambda function to copy the file uploaded to target bucket"
aws lambda invoke --function-name ${LAMBDA_FUNCTION_NAME} response.json
