AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  SourceBucketName:
    Type: String
    Description: The S3 bucket as a files container
  TargetBucketName:
    Type: String
    Description: The S3 bucket will copy files to
  LambdaRole:
    Type: String
    Description: Valid role to create lambda function
  LambdaCode:
    Type: String
    Description: The code of lambda function to deploy

Resources:
  ReadFile:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: lambda_handler
      Handler: index.lambda_handler
      Role: !Ref LambdaRole
      Code:
        ZipFile: !Ref LambdaCode
      Runtime: "python3.7"
      Timeout: 3

  ResourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref SourceBucketName
      NotificationConfiguration:
        LambdaConfigurations:
          Event: s3:ObjectCreated:*
          Filter:
            S3Key:
              Rules:
                - Name: suffix
                  Value: .jpg
          Function: !GetAtt ReadFile

  TargetBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref TargetBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        RestrictPublicBuckets: TRUE
      VersioningConfiguration:
        Status: Enabled
